<script>
	import { api } from '$lib/api.js';
	import { interviewState } from '$lib/stores/interview.js';
	import WaitingDots from '$lib/components/WaitingDots.svelte';
	import { onMount } from 'svelte';

	let { onChangeRoom, onSwitchSession, onLeave } = $props();

	let profiles = $state([]);
	let loading = $state(true);
	let loadError = $state('');

	async function loadProfiles() {
		loading = true;
		loadError = '';
		try {
			const data = await api('workshop-room', {
				params: { sessionId: $interviewState.sessionId, roomId: $interviewState.roomId }
			});
			const room = data.room || data;
			const allProfiles = room.capabilityProfiles || (room.capabilityProfile ? [room.capabilityProfile] : []);
			profiles = allProfiles.filter((p) => p.studentName === $interviewState.studentName);
		} catch (err) {
			loadError = err.message || 'Failed to load profiles';
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		loadProfiles();
	});

	function handleDownloadPDF() {
		const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
		const name = $interviewState.studentName;

		const profilesHTML = profiles.map((p) => {
			const caps = (p.capabilities || []).map((cap) => {
				const capName = typeof cap === 'string' ? cap : cap.capability || cap.name || '';
				const evidence = typeof cap === 'object' ? (cap.evidence || '') : '';
				return `<div class="cap-item">
					<div class="cap-name">${esc(capName)}</div>
					${evidence ? `<div class="cap-evidence">${esc(evidence)}</div>` : ''}
				</div>`;
			}).join('');
			return `<div class="profile-section"><h2>Round ${p.round}</h2><p class="summary">${esc(p.summary || '')}</p><h3>Capabilities Identified</h3><div class="capabilities">${caps}</div></div>`;
		}).join('<hr>');

		const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Capability Profile — ${esc(name)}</title>
<style>
@page{margin:.75in;size:letter}*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Segoe UI',system-ui,-apple-system,sans-serif;color:#1a1a2e;line-height:1.6;padding:40px;max-width:800px;margin:0 auto}.header{text-align:center;margin-bottom:32px;padding-bottom:24px;border-bottom:3px solid #6c63ff}.header h1{font-size:28px;color:#6c63ff;margin-bottom:4px}.header .subtitle{font-size:14px;color:#666}.student-name{font-size:22px;font-weight:600;margin-top:8px;color:#1a1a2e}.profile-section{margin:24px 0}.profile-section h2{font-size:18px;color:#6c63ff;margin-bottom:8px}.profile-section h3{font-size:15px;color:#444;margin:16px 0 10px;text-transform:uppercase;letter-spacing:.5px}.summary{font-size:15px;color:#333;margin-bottom:8px;font-style:italic}.capabilities{display:flex;flex-direction:column;gap:12px}.cap-item{padding:12px 16px;background:#f4f3ff;border-left:4px solid #6c63ff;border-radius:4px}.cap-name{font-weight:600;font-size:15px;color:#1a1a2e}.cap-evidence{font-size:13px;color:#555;margin-top:4px}hr{border:none;border-top:1px solid #ddd;margin:28px 0}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #ddd;text-align:center;font-size:12px;color:#999}.print-bar{text-align:center;padding:16px;margin-bottom:24px;background:#f8f8ff;border-radius:8px}.print-bar button{background:#6c63ff;color:#fff;border:none;padding:10px 28px;border-radius:6px;font-size:15px;cursor:pointer;font-weight:600}.print-bar button:hover{background:#5548d9}.print-bar p{font-size:13px;color:#666;margin-top:6px}@media print{.print-bar{display:none}body{padding:0}.cap-item{break-inside:avoid}.profile-section{break-inside:avoid}}
</style></head><body>
<div class="print-bar"><button onclick="window.print()">Save as PDF</button><p>Use your browser's "Save as PDF" option in the print dialog.</p></div>
<div class="header"><h1>Capability Profile</h1><div class="subtitle">Career Intelligence Workshop</div><div class="student-name">${esc(name)}</div><div class="subtitle">${esc(dateStr)}</div></div>
${profilesHTML}
<div class="footer">Generated by Career Intelligence Workshop &middot; ${esc(dateStr)}</div>
</body></html>`;

		const w = window.open('', '_blank');
		if (w) {
			w.document.write(html);
			w.document.close();
		} else {
			alert('Pop-up blocked. Please allow pop-ups for this site.');
		}
	}

	function esc(str) {
		const d = document.createElement('div');
		d.textContent = str;
		return d.innerHTML;
	}
</script>

<div class="ws-card ws-card--centered">
	<h2>All rounds complete!</h2>
	<p>Great work. Download your capability profile to keep a record of what your peers discovered about you.</p>

	{#if loading}
		<div style="text-align:center;margin-top:12px;">
			<WaitingDots />
			<p style="font-size:14px;color:var(--ci-text-muted);">Loading your profiles...</p>
		</div>
	{:else if loadError}
		<div class="ws-empty-state" style="margin-top:12px;">
			<p class="ws-empty-state__title">Couldn't load your profiles</p>
			<p class="ws-empty-state__text" style="margin-bottom:12px;">{loadError}</p>
			<button class="ws-btn ws-btn--secondary ws-btn--small" onclick={loadProfiles}>Try Again</button>
		</div>
	{:else if profiles.length === 0}
		<p style="color:var(--ci-text-muted);font-size:14px;">No capability profiles found for you yet.</p>
	{:else}
		{#each profiles as p}
			<div class="ws-profile-card ws-profile-card--visible" style="margin-top:16px;">
				<h3>Round {p.round} Profile</h3>
				<p>{p.summary || ''}</p>
				<div class="ws-capability-tags">
					{#each p.capabilities || [] as cap}
						{@const name = typeof cap === 'string' ? cap : cap.capability || cap.name || ''}
						{@const evidence = typeof cap === 'object' ? (cap.evidence || '') : ''}
						<div class="ws-capability-tag">
							<strong>{name}</strong>
							{#if evidence}<br><span style="font-size:13px;color:var(--ci-text-muted)">{evidence}</span>{/if}
						</div>
					{/each}
				</div>
			</div>
		{/each}
	{/if}

	<div class="ws-btn-row" style="justify-content:center;margin-top:20px;">
		<button class="ws-btn" onclick={handleDownloadPDF} disabled={profiles.length === 0}>Download Your Profile (PDF)</button>
	</div>
	<div class="ws-btn-row" style="justify-content:center;margin-top:16px;">
		<button class="ws-btn ws-btn--secondary ws-btn--small" onclick={onChangeRoom}>Back to Rooms</button>
		<button class="ws-btn ws-btn--secondary ws-btn--small" onclick={onSwitchSession}>Join a Different Session</button>
		<button class="ws-btn ws-btn--secondary ws-btn--small" onclick={onLeave}>Leave Session</button>
	</div>
</div>
